name: Build

on:
  push:
    branches:
      - main

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  

      - name: Create Docker network
        run: docker network create sonarnet
  
      - name: Build and start Docker containers on custom network
        run: |
          docker compose up --build -d
          docker network connect sonarnet $(docker ps -q -f name=sonarqube)
          docker ps

  Sonar-Analise:
    name: Sonar-Analise
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  

      - name: Run SonarQube analysis
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://sonarqube:9000
  
      - name: Remove Docker network
        run: docker network rm sonarnet